### ISSUE TITLE
Upgrade all exercises to Cairo 2.7.1

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#119]
https://community.starknet.io/t/cairo-v2-7-0-is-coming/114362

Must complete https://github.com/exercism/cairo-test-runner/issues/12 too

**Comment by BNAndras** [comment]
Could we reference the current version of Cairo being usedon this repo's README? Something like https://github.com/exercism/python/blob/00d5bcc9de36dcd2300b6b05d08cdcf63d660d9b/README.md?plain=1#L22 would be helpful since my `asdf` indicates I've been on 2.7 for a few weeks. The official installation recommended using `asdf` so students may similarly end up on a newer version than Exercism supports.

**Comment by 0xNeshi** [comment]
@BNAndras sounds good, will update

**Comment by 0xNeshi** [comment]
@BNAndras Cairo 2.8.0 is out, so will be updating to this version
https://community.starknet.io/t/cairo-v2-8-0-is-out/114606
